[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
pool_size = 10

[deployment]
[[deployment.rule]]
store = "primary"
indexers = ["default"]

[chains]
ingestor = "default"

[chains.mainnet]
shard = "primary"
provider = [
  { label = "erpc", url = "https://eth-mainnet.blastapi.io/5a41b4fd-8f3c-4060-9cdc-521ba39e0a90", features = ["archive"] }
]
