{
 "title": "Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROM", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Deployments (uniswap-v2-latest-no-config-defaults)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  d.deployment,\n  i.name,\n  d.failed,\n  d.latest_ethereum_block_number,\n  d.entity_count,\n  d.reorg_count,\n  d.current_reorg_depth,\n  d.max_reorg_depth,\n  d.health,\n  d.synced_at\nFROM subgraphs.subgraph_deployment d\nJOIN info.subgraph_info i ON i.subgraph = d.deployment\nORDER BY d.deployment DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Errors (uniswap-v2-latest-no-config-defaults)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  e.subgraph_id,\n  i.name,\n  e.message,\n  e.block_range,\n  e.deterministic,\n  e.created_at\nFROM subgraphs.subgraph_error e\nJOIN info.subgraph_info i ON i.subgraph = e.subgraph_id\nORDER BY e.created_at DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Deployments (uniswap-v3-latest-no-config-defaults)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  d.deployment,\n  i.name,\n  d.failed,\n  d.latest_ethereum_block_number,\n  d.entity_count,\n  d.reorg_count,\n  d.current_reorg_depth,\n  d.max_reorg_depth,\n  d.health,\n  d.synced_at\nFROM subgraphs.subgraph_deployment d\nJOIN info.subgraph_info i ON i.subgraph = d.deployment\nORDER BY d.deployment DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Errors (uniswap-v3-latest-no-config-defaults)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  e.subgraph_id,\n  i.name,\n  e.message,\n  e.block_range,\n  e.deterministic,\n  e.created_at\nFROM subgraphs.subgraph_error e\nJOIN info.subgraph_info i ON i.subgraph = e.subgraph_id\nORDER BY e.created_at DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Deployments (uniswap-v4-latest-no-config-defaults)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  d.deployment,\n  i.name,\n  d.failed,\n  d.latest_ethereum_block_number,\n  d.entity_count,\n  d.reorg_count,\n  d.current_reorg_depth,\n  d.max_reorg_depth,\n  d.health,\n  d.synced_at\nFROM subgraphs.subgraph_deployment d\nJOIN info.subgraph_info i ON i.subgraph = d.deployment\nORDER BY d.deployment DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Errors (uniswap-v4-latest-no-config-defaults)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  e.subgraph_id,\n  i.name,\n  e.message,\n  e.block_range,\n  e.deterministic,\n  e.created_at\nFROM subgraphs.subgraph_error e\nJOIN info.subgraph_info i ON i.subgraph = e.subgraph_id\nORDER BY e.created_at DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "RPC Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(eth_rpc_request_duration_sum[1m])",
     "legendFormat": "{{job}} - {{method}}"
    }
   ]
  },
  {
   "title": "Block Processing Duration",
   "type": "barchart",
   "description": "Measures duration of block processing for a subgraph deployment",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(deployment_block_processing_duration_bucket[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trigger Processing Duration",
   "type": "barchart",
   "description": "Measures duration of trigger processing for a subgraph deployment",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(deployment_trigger_processing_duration_bucket[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler Execution Time",
   "type": "barchart",
   "description": "Measures the execution time for handlers",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, handler, le) (rate(deployment_handler_execution_time_bucket[5m])))",
     "legendFormat": "{{job}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Syncing Progress",
   "type": "barchart",
   "description": "Calculates percentage of syncing progress by subtracting most recent block synced from head block number",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "(deployment_head / on() group_left() max(ethereum_chain_head_number)) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "eRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "P95 resp. time",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, job, network, upstream)) > 0",
     "legendFormat": "{{job}} / {{upstream}} / {{network}}"
    }
   ]
  },
  {
   "title": "Network-level Requests",
   "type": "timeseries",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_request_received_total[30s])) by (job, project, network, category)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket[30s])) by (le, job, project, network, category))",
     "legendFormat": "p50: {{job}}, {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_network_request_duration_seconds_bucket[30s])) by (le, job, project, network, category))",
     "legendFormat": "p95: {{job}}, {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket[5m])) by (le, job, project, network, category))",
     "legendFormat": "p99: {{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_received_total[30s])) by (job, project, network, category)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network self-imposed Rate-limited requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_self_rate_limited_total[30s])) by (job, project, network, category)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Errors",
   "type": "timeseries",
   "description": "When a request fails even after trying all upstreams and retries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_failed_request_total[30s])) by (job,project,network,error) > 0",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level requests",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_total[30s])) by (job, project, network, upstream, attempt)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}, {{attempt}}"
    }
   ]
  },
  {
   "title": "Upstream-level RPS",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_total[30s])) by (job, project, network, upstream, attempt)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}, {{attempt}}"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 196 },
   "targets": [
    {
     "expr": "avg(erpc_upstream_score_overall{network=\"*\"}) by (job, project, upstream, network)",
     "legendFormat": "{{job}}, {{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level self-imposed Ratel-limited requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 196 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_self_rate_limited_total[30s])) by (job, project, network, upstream)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level Remote rate-limited Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 208 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_remote_rate_limited_total[30s])) by (job, project, network, upstream)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Rate-limit budget MaxCount",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 208 },
   "targets": [
    {
     "expr": "sum by (budget, method) (erpc_rate_limiter_budget_max_count)",
     "legendFormat": "{{budget}}, {{method}}"
    }
   ]
  },
  {
   "title": "Upstream-level resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 220 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket[30s])) by (le, job, project, upstream))",
     "legendFormat": "p50: {{job}}, {{project}}, {{upstream}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket[30s])) by (le, job, project, upstream))",
     "legendFormat": "p95: {{job}}, {{project}}, {{upstream}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket[1m])) by (le, job, project, upstream))",
     "legendFormat": "p99: {{job}}, {{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Method resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 220 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, project, network, upstream, category))",
     "legendFormat": "p50: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, project, network, upstream, category))",
     "legendFormat": "p95: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[1m])) by (le, project, network, upstream, category))",
     "legendFormat": "p99: {{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level warning errors",
   "type": "timeseries",
   "description": "Failures from upstream endpoints (rate-limit, etc.)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 232 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"warning\"}[30s])) by (job, project, network, upstream, error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level critical errors",
   "type": "timeseries",
   "description": "Critical errors from upstream endpoints",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 244 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"critical\"}[30s])) by (job, project, network, upstream, error) > 0",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Cache SET success total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 262 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_success_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 262 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_error_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-hit total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 272 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_hit_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-miss total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 272 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_miss_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 282 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_error_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 282 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_error_duration_seconds_bucket[30s])) by (le, job, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_error_duration_seconds_bucket[30s])) by (le, job, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Deployments (uniswap-v3-latest-only-network-level-failsafe)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  d.deployment,\n  i.name,\n  d.failed,\n  d.latest_ethereum_block_number,\n  d.entity_count,\n  d.reorg_count,\n  d.current_reorg_depth,\n  d.max_reorg_depth,\n  d.health,\n  d.synced_at\nFROM subgraphs.subgraph_deployment d\nJOIN info.subgraph_info i ON i.subgraph = d.deployment\nORDER BY d.deployment DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Errors (uniswap-v3-latest-only-network-level-failsafe)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  e.subgraph_id,\n  i.name,\n  e.message,\n  e.block_range,\n  e.deterministic,\n  e.created_at\nFROM subgraphs.subgraph_error e\nJOIN info.subgraph_info i ON i.subgraph = e.subgraph_id\nORDER BY e.created_at DESC\nLIMIT 100;"
    }
   ]
  }
 ]
}