{
 "title": "Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROM", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Ponder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Historical Sync Progress",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n* sum by (job) (ponder_historical_completed_blocks)\n/\nsum by (job) (ponder_historical_total_blocks)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ponder Indexing Error",
   "type": "stat",
   "description": "Boolean (0 or 1) indicating if there is an indexing error",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ponder_indexing_has_error", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Found Cached Blocks",
   "type": "stat",
   "description": "Number of blocks that were found in the cache for the historical sync",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ponder_historical_cached_blocks) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPC Request Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ponder_rpc_request_duration_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Request Lag (p95)",
   "type": "timeseries",
   "description": "Time RPC requests spend waiting in the request queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ponder_rpc_request_lag_bucket[$__rate_interval])) by (le, job))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "timeseries",
   "description": "Number of events that have been processed",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "sum by (job) (ponder_indexing_completed_events)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ponder Realtime Enabled?",
   "type": "stat",
   "description": "Boolean (0 or 1) indicating if the realtime sync service is connected",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ponder_realtime_is_connected", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Reorg Happened?",
   "type": "stat",
   "description": "Count of how many re-orgs have occurred",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ponder_realtime_is_connected", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Sync store method duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, max by(le, method) (increase(ponder_database_method_duration_bucket{service=\"sync\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Indexing method duration (p90)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, max by(le, method) (increase(ponder_database_method_duration_bucket{service=\"indexing\"}[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "[Postgres] Query rate",
   "type": "timeseries",
   "description": "Rate of queries submitted to the database",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(pool) (rate(ponder_postgres_query_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "eRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Network-level Requests",
   "type": "timeseries",
   "description": "Total requests received by eRPC for a specific network and method",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_request_received_total[30s])) by (job, project, network, category)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_network_request_duration_seconds_bucket[30s])) by (le, job, project, network, category))",
     "legendFormat": "p50: {{job}}, {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_network_request_duration_seconds_bucket[30s])) by (le, job, project, network, category))",
     "legendFormat": "p95: {{job}}, {{project}}, {{network}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_network_request_duration_seconds_bucket[5m])) by (le, job, project, network, category))",
     "legendFormat": "p99: {{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_received_total[30s])) by (job, project, network, category)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network self-imposed Rate-limited requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_network_request_self_rate_limited_total[30s])) by (job, project, network, category)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}"
    }
   ]
  },
  {
   "title": "Network-level Errors",
   "type": "timeseries",
   "description": "When a request fails even after trying all upstreams and retries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_network_failed_request_total[30s])) by (job,project,network,error) > 0",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level requests",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_total[30s])) by (job, project, network, upstream, attempt)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}, {{attempt}}"
    }
   ]
  },
  {
   "title": "Upstream-level RPS",
   "type": "timeseries",
   "description": "These are real requests sent to upstream endpoints, including retries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(erpc_upstream_request_total[30s])) by (job, project, network, upstream, attempt)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}, {{attempt}}"
    }
   ]
  },
  {
   "title": "Scores",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "avg(erpc_upstream_score_overall{network=\"*\"}) by (job, project, upstream, network)",
     "legendFormat": "{{job}}, {{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level self-imposed Ratel-limited requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_self_rate_limited_total[30s])) by (job, project, network, upstream)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Upstream-level Remote rate-limited Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_remote_rate_limited_total[30s])) by (job, project, network, upstream)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Rate-limit budget MaxCount",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "sum by (budget, method) (erpc_rate_limiter_budget_max_count)",
     "legendFormat": "{{budget}}, {{method}}"
    }
   ]
  },
  {
   "title": "Upstream-level resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket[30s])) by (le, job, project, upstream))",
     "legendFormat": "p50: {{job}}, {{project}}, {{upstream}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket[30s])) by (le, job, project, upstream))",
     "legendFormat": "p95: {{job}}, {{project}}, {{upstream}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket[1m])) by (le, job, project, upstream))",
     "legendFormat": "p99: {{job}}, {{project}}, {{upstream}}"
    }
   ]
  },
  {
   "title": "Method resp. time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 147 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, project, network, upstream, category))",
     "legendFormat": "p50: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[30s])) by (le, project, network, upstream, category))",
     "legendFormat": "p95: {{project}}, {{network}}, {{upstream}}, {{category}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(erpc_upstream_request_duration_seconds_bucket{network!=\"n/a\"}[1m])) by (le, project, network, upstream, category))",
     "legendFormat": "p99: {{project}}, {{network}}, {{upstream}}, {{category}}"
    }
   ]
  },
  {
   "title": "Upstream-level warning errors",
   "type": "timeseries",
   "description": "Failures from upstream endpoints (rate-limit, etc.)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"warning\"}[30s])) by (job, project, network, upstream, error) > 0",
     "legendFormat": "{{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Upstream-level critical errors",
   "type": "timeseries",
   "description": "Critical errors from upstream endpoints",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum(increase(erpc_upstream_request_errors_total{severity=\"critical\"}[30s])) by (job, project, network, upstream, error) > 0",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{upstream}}, {{error}}"
    }
   ]
  },
  {
   "title": "Cache SET success total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_success_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache SET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 189 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_set_error_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-hit total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 199 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_hit_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET success-miss total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 199 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_success_miss_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 209 },
   "targets": [
    {
     "expr": "sum(increase(erpc_cache_get_error_total[30s])) by (job, project, network, category, connector, policy, ttl)",
     "legendFormat": "{{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  },
  {
   "title": "Cache GET error duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 209 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(erpc_cache_get_error_duration_seconds_bucket[30s])) by (le, job, project, network, category, connector, policy, ttl))",
     "legendFormat": "p50 - {{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(erpc_cache_get_error_duration_seconds_bucket[30s])) by (le, job, project, network, category, connector, policy, ttl))",
     "legendFormat": "p95 - {{job}}, {{project}}, {{network}}, {{category}}, {{connector}}, {{policy}}, TTL={{ttl}}"
    }
   ]
  }
 ]
}