version: "3.8"

services:
  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command:
      - postgres
      - "-cshared_preload_libraries=pg_stat_statements"
      - "-cmax_connections=200"
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      driver: local
      options:
        max-size: 5M
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d graph-node -U graph-node"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      default: {}

  ipfs:
    image: ipfs/kubo:v0.14.0
    ports:
      - "${IPFS_PORT:-5001}:5001"
    volumes:
      - ./data/ipfs:/data/ipfs
    logging:
      driver: local
      options:
        max-size: 5M
        max-file: "3"
    healthcheck:
      test: ["CMD", "ipfs", "id"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      default: {}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    logging:
      driver: local
      options:
        max-size: 5M
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      default: {}

  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "${GRAPH_NODE_PORT1:-8000}:8000"
      - "${GRAPH_NODE_PORT2:-8001}:8001"
      - "${GRAPH_NODE_PORT3:-8020}:8020"
      - "${GRAPH_NODE_PORT4:-8030}:8030"
      - "${GRAPH_NODE_PORT5:-8040}:8040"
    depends_on:
      ipfs:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./config.toml:/etc/config/config.toml
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: ipfs:5001
      GRAPH_LOG: info
      GRAPH_NODE_CONFIG: /etc/config/config.toml
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: changeme
      ERPC_HTTP_PORT: ${ERPC_HTTP_PORT:-4000}
    restart: on-failure
    platform: linux/amd64
    networks:
      default: {}

volumes:
  esdata: {}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
