services:
  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    command:
      - postgres
      - "-cshared_preload_libraries=pg_stat_statements"
      - "-cmax_connections=200"
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    logging:
      driver: local
      options:
        max-size: 5M
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d graph-node -U graph-node"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      default: {}

  # ipfs:
  #   image: ipfs/kubo:v0.14.0
  #   ports:
  #     - "${IPFS_PORT:-5001}:5001"
  #   volumes:
  #     - ipfsdata:/data/ipfs
  #   logging:
  #     driver: local
  #     options:
  #       max-size: 5M
  #       max-file: "3"
  #   healthcheck:
  #     test: ["CMD", "ipfs", "id"]
  #     interval: 1s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     default: {}

  graph-node:
    image: ${GRAPH_NODE_IMAGE:-graphprotocol/graph-node}
    ports:
      - "${GRAPH_NODE_PORT1:-8000}:8000"
      - "${GRAPH_NODE_PORT2:-8001}:8001"
      - "${GRAPH_NODE_PORT3:-8020}:8020"
      - "${GRAPH_NODE_PORT4:-8030}:8030"
      - "${GRAPH_NODE_PORT5:-8040}:8040"
    depends_on:
      # ipfs:
      #   condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./config.toml:/etc/config/config.toml
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: host.docker.internal:5001
      OTEL_SERVICE_NAME: graph-${NETWORK_NAME:-default}
      # OTEL_EXPORTER_JAEGER_ENDPOINT: http://host.docker.internal:14268/api/traces
      OTEL_EXPORTER_JAEGER_AGENT_HOST: host.docker.internal
      OTEL_EXPORTER_JAEGER_AGENT_PORT: 6832
      DATADOG_OTEL_HOST: any.dummy.value
      DATADOG_OTEL_PORT: 1111
      # OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      # OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
      # OTEL_EXPORTER_JAEGER_AGENT_PORT: 6832
      # OTEL_EXPORTER_JAEGER_PROTOCOL: http/thrift.binary
      RUST_LOG: warn,graph=info,graph_node::otel=debug,opentelemetry=debug
      OTEL_SPAN_FILTER: graph_chain_ethereum,reqwest_tracing::reqwest_otel_span_builder
      # OTEL_TRACES_EXPORTER: jaeger
      # OTEL_TRACES_SAMPLER: parentbased_traceidratio
      # OTEL_TRACES_SAMPLER_ARG: "1.0"  # Sample 100% of traces, adjust as needed
      GRAPH_LOG: ${GRAPH_LOG_LEVEL:-error}
      GRAPH_NODE_CONFIG: /etc/config/config.toml
      ERPC_HTTP_PORT: ${ERPC_HTTP_PORT:-4000}
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: ${GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE}
      GRAPH_ETHEREUM_MAX_EVENT_ONLY_RANGE: ${GRAPH_ETHEREUM_MAX_EVENT_ONLY_RANGE}
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: ${GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE}
      ETHEREUM_BLOCK_BATCH_SIZE: ${ETHEREUM_BLOCK_BATCH_SIZE}
      # GRAPH_ETHEREUM_BLOCK_INGESTOR_MAX_CONCURRENT_JSON_RPC_CALLS_FOR_TXN_RECEIPTS: 100
    restart: on-failure
    platform: linux/amd64
    networks:
      - default
      - monitoring

volumes:
  ipfsdata: {}
  postgresdata: {}
  esdata: {}

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
  monitoring:
    external: true
    name: monitoring